apiVersion: v1
kind: Service
metadata:
  name: fllower
  labels:
    app: airflow
    tier: flower
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
      nodePort: 30570
  selector:
    app: airflow
    tier: flower
