apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: airflow
    tier: webserver
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31050
  selector:
    app: airflow
    tier: webserver
