apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    tier: webserver
    app: airflow
  name: webserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: webserver
        app: airflow
    spec:
      containers:
      - args:
        - webserver
        env:
        - name: EXECUTOR
          value: Celery
        - name: FERNET_KEY
          value: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - name: LOAD_EX
          value: "n"
        image: chiju/airflow
        name: webserver
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/airflow/airflow.cfg
          name: config-volume
          subPath: airflow.cfg
      restartPolicy: Always
      volumes:
      - name: config-volume
        configMap:
          name: airflow.cfg
